apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80  
  - name: frontal
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["watch", "-n5", "ping",  "localhost"]
