apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-03T21:07:46Z"
  labels:
    name: nginx
  name: nginx
  namespace: default
  resourceVersion: "34548"
  uid: 5a62c818-e139-4751-b83e-d727513aa937
spec:
  containers:
  - image: juampymdd/nginx:v1
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-86jt6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-86jt6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-03T21:07:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-03T21:07:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-03T21:07:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-03T21:07:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c7d3aa8eafba0be9fda9e2c8d5a863ea27a3a337cb11b41efdb456ea3922e286
    image: juampymdd/nginx:v1
    imageID: docker-pullable://juampymdd/nginx@sha256:59923b276452c956fe29593e8abb7cff0d2e36d22350fd84520e25ae69601d65
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-03T21:07:47Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.13
  podIPs:
  - ip: 10.1.0.13
  qosClass: Guaranteed
  startTime: "2024-01-03T21:07:46Z"
