apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
   - name: tomcat     
     image: tomcat
     resources:
       limits:
         memory: "128Mi"
         cpu: "500m"
  restartPolicy: Always
